# Generated by Django 3.0.5 on 2020-05-22 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='DemoJob',
            fields=[
                ('name', models.CharField(max_length=128, blank=True, default="")),
                ('job_name', models.CharField(max_length=128)),
            ],
        ),
    ]
